services:
  postgres:
    image: postgres:16
    container_name: queue_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: studhub_db
      POSTGRES_USER: studhub_admin
      POSTGRES_PASSWORD: SuperSecurePassword1

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_data: